export const N_POSSIBILITY = 12;
export const M_POSSIBILITY = 20;
export const PRICE_1 = 60;
export const PRICE_2 = 54;
export const PRICE_3 = 48;
export const PRICE_4 = 36;
export const PRICE_SALVAGE = 25;
export const INIT_STOCK = 2000;
export const POSSIBLE_PRICES = [PRICE_1, PRICE_2, PRICE_3, PRICE_4];
